# -*- coding: utf-8 -*-
"""ICT_Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xuoPgKRO9FslhpuI3D8UFbGjU3UBtlzJ
"""

# IMPORT REQUIRED LIBRARIES


import pandas as pd                     # Data handling and DataFrame creation
import numpy as np                      # Numerical operations
import matplotlib.pyplot as plt         # Plotting graphs
from datetime import datetime           # Date and time handling

# Machine Learning libraries
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, classification_report



# PROCEDURAL LOG FILE PARSING


file_path = "Data set.csv"              # Raw cloud-CAD log file

parsed_data = []                        # List to store parsed log records

with open(file_path, 'r') as file:
    header = file.readline().strip().split(',')  # Read header row manually

    for line in file:
        if line.strip() == "": continue                   # Skip empty lines

        values = line.strip().split(',')  # Split each line into fields
        record = {}

        # Map each value to its corresponding column name
        for i in range(len(header)):            record[header[i]] = values[i]


# TYPE CONVERSION (MANUAL)


        # Convert session start time to time object
        record['SessionStart'] = datetime.strptime(record['SessionStart'], "%I:%M %p").time()

        # Convert numeric fields from string to correct data type
        record['SessionUser ratio(min)'] = float(record['SessionUser ratio(min)'])
        record['IdleTime(min)'] = float(record['IdleTime(min)'])
        record['TotalEdits'] = int(record['TotalEdits'])
        record['EditDensity'] = float(record['EditDensity'])
        record['IdleRatio'] = float(record['IdleRatio'])

        parsed_data.append(record)      # Store parsed record



# CREATE DATAFRAME FROM PARSED DATA


df = pd.DataFrame(parsed_data)

print("Parsed Dataset:")
print(df.head())

print("\nDataset Information:")
print(df.info())

print("\nStatistical Summary:")
print(df.describe())


# LABEL ENCODING (TARGET VARIABLE)

# Convert productivity labels (Low, Medium, High) to numeric form
le = LabelEncoder()
df['ProdUser Activity'] = le.fit_transform(df['ProdUser Activity'])

print("\nAfter Label Encoding:")
print(df[['ProdUser Activity']].head())

# FEATURE SELECTION & DATA SPLIT


features = ['SessionUser ratio(min)','IdleTime(min)','EditDensity', 'IdleRatio']

target = 'ProdUser Activity'

X = df[features]           # Independent variables
y = df[target]             # Dependent variable

# Split dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=50)

print("\nTrain-Test Shapes:")
print(X_train.shape, X_test.shape)

# MODEL TRAINING (DECISION TREE)

# Standardize features
scaler = StandardScaler()

X_train_scaled = pd.DataFrame(scaler.fit_transform(X_train),columns=X_train.columns)

X_test_scaled = pd.DataFrame(scaler.transform(X_test),columns=X_test.columns)


dt = DecisionTreeClassifier()  # Decision Tree Classifier
dt.fit(X_train_scaled, y_train)                # Train model

y_pred = dt.predict(X_test_scaled)      # Predict productivity classes

# MODEL EVALUATION

accuracy = accuracy_score(y_test, y_pred)
print(f"\nModel Accuracy: {accuracy}")

print("\nClassification Report:")
print(classification_report(y_test, y_pred, zero_division=0))

# 24-HOUR PRODUCTIVITY RADAR CHART

# Extract hour from session start time
df['Hour'] = df['SessionStart'].apply(lambda x: x.hour)

# Map encoded productivity values to meaningful scores
# High → 2, Medium → 1, Low → 0
productivity_map_numeric = {0: 2, 1: 0, 2: 1}
df['ProdScore'] = df['ProdUser Activity'].map(productivity_map_numeric)

# Session duration used for normalization
df['Duration'] = df['SessionUser ratio(min)']

# Calculate hourly average productivity and duration
hourly_metrics = df.groupby('Hour').agg({'ProdScore': 'mean','Duration': 'mean'})

# Ensure all 24 hours are represented
hours = list(range(24))
hourly_metrics = hourly_metrics.reindex(hours, fill_value=0)

prod_values = [hourly_metrics['ProdScore'].get(h, 0) for h in hours]
dur_values = [hourly_metrics['Duration'].get(h, 0) for h in hours]

# Normalize duration values to a scale of 0–10
max_duration = max(dur_values) if max(dur_values) != 0 else 1
dur_values = [(d / max_duration) * 10 for d in dur_values]

# Prepare angles for radar plot
angles = np.linspace(0, 2 * np.pi, 24, endpoint=False)
angles = np.append(angles, angles[0])

# Close radar chart loop
prod_values += prod_values[:1]
dur_values += dur_values[:1]

# Plot radar chart
plt.figure(figsize=(9, 9))
ax = plt.subplot(111, polar=True)

#preparing angles for the radar chart

ax.plot(angles, prod_values, color='purple', label="User Productivity Score")
ax.fill(angles, prod_values, alpha=0.3)

ax.plot(angles, dur_values, color='pink', label="Normalized Session Duration") # changes color of graph to pink and purple
ax.fill(angles, dur_values, alpha=0.3)

ax.set_xticks(angles[:-1])
ax.set_xticklabels([f"{h}:00" for h in hours])
ax.set_ylim(0, 10)

plt.title("24-Hour Radar Chart: Session Duration vs User Productivity")
plt.legend(loc="upper right")
plt.show()

import pandas as pd
from google.colab import files
uploaded = files.upload()